export default actionTypes = {
  CHANGE_NAME: 'CHANGE_NAME',
  PUSH_BUTTON: 'PUSH_BUTTON',
  GET_WINNERS: 'GET_WINNERS',
  PUSH_RESPONSE: 'PUSH_RESPONSE',
  PUSH_SUCCESS: 'PUSH_SUCCESS',
  CONNECTION_SUCCESS: 'CONNECTION_SUCCESS',
  WINNER_LIST: 'WINNER_LIST',
  SET_PUSHABLE: 'SET_PUSHABLE',
};